version: '3.9'
services:
  search:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: medical-record-search
    hostname: search
    expose:
      #- "5000"
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./:usr/app
    command: npm run start