export const response = {
    "status": "success",
    "statusCode": 200,
    "patient": {
        "id": 1,
        "externalPatientId": "12345",
        "firstName": "Alice",
        "lastName": "Liddell",
        "sex": "FEMALE",
        "dateOfBirth": "1988-09-30",
        "stateCode": "CA",
        "email": "alice@gmail.com",
        "phone": "(209) 777-4547",
        "addressLine1": "123 Main Street",
        "addressLine2": null,
        "city": "Merced",
        "state": "CA",
        "postalCode": "95348",
        "paymentType": "CASH",
        "dateOfConsent": "2020-08-30T00:00:00.000Z",
        "truepillPatientToken": "truepillPatientToken123",
        "stripeCustomerId": "stripe_123",
        "prescriptions": [
            {
                "id": 1,
                "prescriberCompany": "MedLife",
                "prescriberAddressLine1": "333 J Street",
                "prescriberAddressLine2": null,
                "prescriberCity": "San Francisco",
                "prescriberState": "CA",
                "prescriberPostalCode": "95443",
                "prescriberPhone": "(415) 333-8899",
                "prescriberLicenseNumber": "3sd34dds",
                "prescriberSignature": "M Dawson",
                "deaNumber": "3dkf3f",
                "npi": "3223425",
                "rxSignature": "1$23409dfu0902945323094234",
                "dateWritten": "2023-05-25T22:36:38.550Z",
                "ndc": "0645345245",
                "medication": "Sprintec",
                "quantity": 4,
                "unit": "Pack(s)",
                "sig": "One at a time",
                "indication": "some indication",
                "refills": 4,
                "daw": true,
                "truepillRxToken": "truepillRxToken23234",
                "patientId": 1
            },
            {
                "id": 1,
                "prescriberCompany": "MedLife",
                "prescriberAddressLine1": "333 J Street",
                "prescriberAddressLine2": null,
                "prescriberCity": "San Francisco",
                "prescriberState": "CA",
                "prescriberPostalCode": "95443",
                "prescriberPhone": "(415) 333-8899",
                "prescriberLicenseNumber": "3sd34dds",
                "prescriberSignature": "M Dawson",
                "deaNumber": "3dkf3f",
                "npi": "3223425",
                "rxSignature": "1$234sdfsdfe34234234",
                "dateWritten": "2023-05-25T22:36:38.550Z",
                "ndc": "0234234234234",
                "medication": "Ella",
                "quantity": 1,
                "unit": "Pack(s)",
                "sig": "One at a time",
                "indication": "some indication",
                "refills": 1,
                "daw": true,
                "truepillRxToken": "truepillRxToken5556677",
                "patientId": 1
            }
        ],
        "consultations": [
            {
                "createdAt": "2023-06-13T01:12:30Z",
                "abdominalOrPelvicSurgeries": null,
                "alcoholUsage": "NEVER",
                "allergies": true,
                "allergiesNote": "Aspirin",
                "averageMenstrualCycle": "VARIES",
                "bloating": false,
                "bloodClots": null,
                "bloodClotsNote": null,
                "bloodPressure": "100-139/60-89",
                "breastPainBeforePeriod": null,
                "cervicalDysplasiaOrAbnormalPaps": null,
                "coldSoresFrequency": 'NINE_OR_LESS_PER_YEAR',
                "consentToTelehealth": "Agree",
                "currentBirthControl": null,
                "currentBirthControlNote": null,
                "currentColdSoresOutbreak": true,
                "currentGenitalHerpesOutbreak": false,
                "decreasedLibido": null,
                "diabetes": false,
                "diabetesNote": null,
                "difficultySleeping": false,
                "drospirenoneWaiver": false,
                "endometriosis": null,
                "excessHairGrowth": null,
                "exerciseFrequency": null,
                "fibroids": null,
                "genitalHerpesFrequency": 'NINE_OR_LESS_PER_YEAR',
                "givenBirth": true,
                "hadPeriodInPastYear": true,
                "hairLoss": null,
                "heartConditions": null,
                "heartConditionsNote": null,
                "height": "68",
                "herpesConsultConditions": null,
                "herpesConsultMedications": null,
                "highBloodPressure": false,
                "highBloodPressureNote": null,
                "highProlactinLevel": null,
                "hivOrAids": false,
                "hotFlashesOrNightSweats": null,
                "irritabilityAnxietyDepressionOrWorseningPMS": null,
                "isBreastfeeding": false,
                "isGenericOk": false,
                "liverConditions": null,
                "liverConditionsNote": null,
                "loseBalanceOrTripEasily": null,
                "medications": null,
                "medicationsNote": null,
                "menstrualCycleDetails": null,
                "migraines": false,
                "monthlyMenstrualCycles": true,
                "otherConditions": false,
                "otherConditionsNote": null,
                "ovarianCysts": null,
                "painBowelMovements": null,
                "painDeepPenetrativeSex": null,
                "painPelvic": null,
                "patchesOfThickenedDarkenedSkin": null,
                "periodPreference": "MONTHLY",
                "polycysticOvarianSyndrome": null,
                "pregnant": false,
                "previousBirthControlPart1": false,
                "previousBirthControlPart2": null,
                "previousBirthControlPart2Note": null,
                "previouslyDiagnosedColdSores": true,
                "previouslyDiagnosedGenitalHerpes": false,
                "primaryReason": null,
                "progestinOnlyPillQuestions": null,
                "questionsForDoctor": null,
                "questionsForDoctorNote": null,
                "recentVaricellaOrZosterVaccination": false,
                "regularMenstrualCycles": 'Yes',
                "rheumatologicOrAutoimmuneDisorder": null,
                "severeAcne": null,
                "severeMenstrualCramping": null,
                "sexuallyTransmittedInfection": null,
                "sideEffectConcerns": null,
                "sideEffectConcernsNote": null,
                "stateCode": "CA",
                "supplements": null,
                "surgeries": null,
                "surgeriesNote": null,
                "thyroidDisorder": true,
                "tobacco": null,
                "tobaccoNote": null,
                "tobaccoUsage": null,
                "usingHormonalBirthControl": null,
                "uterinePolyps": null,
                "vaginalDrynessOrPainWithSex": null,
                "weight": "130",
                "weightGain": false,
            },
            {
                "createdAt": "2023-06-16T01:12:30Z",
                "abdominalOrPelvicSurgeries": null,
                "alcoholUsage": "NEVER",
                "allergies": true,
                "allergiesNote": "Tylenol",
                "averageMenstrualCycle": "VARIES",
                "bloating": false,
                "bloodClots": null,
                "bloodClotsNote": null,
                "bloodPressure": "100-139/60-89",
                "breastPainBeforePeriod": null,
                "cervicalDysplasiaOrAbnormalPaps": null,
                "coldSoresFrequency": 'NINE_OR_LESS_PER_YEAR',
                "consentToTelehealth": "Agree",
                "currentBirthControl": null,
                "currentBirthControlNote": null,
                "currentColdSoresOutbreak": true,
                "currentGenitalHerpesOutbreak": false,
                "decreasedLibido": null,
                "diabetes": false,
                "diabetesNote": null,
                "difficultySleeping": false,
                "drospirenoneWaiver": false,
                "endometriosis": null,
                "excessHairGrowth": null,
                "exerciseFrequency": null,
                "fibroids": null,
                "genitalHerpesFrequency": 'NINE_OR_LESS_PER_YEAR',
                "givenBirth": true,
                "hadPeriodInPastYear": true,
                "hairLoss": null,
                "heartConditions": null,
                "heartConditionsNote": null,
                "height": "68",
                "herpesConsultConditions": null,
                "herpesConsultMedications": null,
                "highBloodPressure": true,
                "highBloodPressureNote": null,
                "highProlactinLevel": null,
                "hivOrAids": false,
                "hotFlashesOrNightSweats": null,
                "irritabilityAnxietyDepressionOrWorseningPMS": true,
                "isBreastfeeding": true,
                "isGenericOk": true,
                "liverConditions": null,
                "liverConditionsNote": null,
                "loseBalanceOrTripEasily": null,
                "medications": null,
                "medicationsNote": null,
                "menstrualCycleDetails": null,
                "migraines": true,
                "monthlyMenstrualCycles": true,
                "otherConditions": false,
                "otherConditionsNote": null,
                "ovarianCysts": null,
                "painBowelMovements": null,
                "painDeepPenetrativeSex": null,
                "painPelvic": true,
                "patchesOfThickenedDarkenedSkin": null,
                "periodPreference": "SKIP",
                "polycysticOvarianSyndrome": null,
                "pregnant": false,
                "previousBirthControlPart1": false,
                "previousBirthControlPart2": null,
                "previousBirthControlPart2Note": null,
                "previouslyDiagnosedColdSores": true,
                "previouslyDiagnosedGenitalHerpes": false,
                "primaryReason": null,
                "progestinOnlyPillQuestions": null,
                "questionsForDoctor": null,
                "questionsForDoctorNote": null,
                "recentVaricellaOrZosterVaccination": false,
                "regularMenstrualCycles": 'Yes',
                "rheumatologicOrAutoimmuneDisorder": null,
                "severeAcne": null,
                "severeMenstrualCramping": null,
                "sexuallyTransmittedInfection": null,
                "sideEffectConcerns": null,
                "sideEffectConcernsNote": null,
                "stateCode": "CA",
                "supplements": null,
                "surgeries": null,
                "surgeriesNote": null,
                "thyroidDisorder": true,
                "tobacco": null,
                "tobaccoNote": null,
                "tobaccoUsage": null,
                "usingHormonalBirthControl": null,
                "uterinePolyps": true,
                "vaginalDrynessOrPainWithSex": null,
                "weight": "130",
                "weightGain": false,
            }
        ],
        "insurancePolicies": [
            {
                "id": 1,
                "memberName": "Alice Liddel",
                "memberId": "122132342345GHGK",
                "planName": "Aetna",
                "rxGroup": "WSG",
                "rxBin": "009214",
                "pcn": "IS",
                "isMedicaid": false,
                "patientId": 1
            }, 
            {
                "id": 1,
                "memberName": "Alice Liddel",
                "memberId": "2345HDFGDDDEEEF",
                "planName": "Anthem Blue Cross",
                "rxGroup": "HHHJJJKKKKK",
                "rxBin": "323434",
                "pcn": "JK",
                "isMedicaid": false,
                "patientId": 1
            },
            {
                "id": 1,
                "memberName": "Alice Liddel",
                "memberId": "23423fasfffff",
                "planName": "Cigna",
                "rxGroup": "TFR",
                "rxBin": "033450",
                "pcn": "DE",
                "isMedicaid": false,
                "patientId": 1
            }

        ]
    }
}